<a href="https://colab.research.google.com/github/Asifleopard08/PIAIC74044_ASSIGNMENT2/blob/main/PIAIC74044_ASSIGNMENT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
                                           ### NUMPY ASSIGNMENT#02
                                           ###MUHAMMAD ASIF
                                           ### PIAIC#74044
import numpy as np

In [9]:
#Question:1
#Convert a 1D array to a 2D array with 2 rows?
#array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
X = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
#Question:2
#How to stack two arrays vertically?
#Desired Output::
#array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
Y = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
Z = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
Z_1 = np.vstack((Y, Z))
Z_1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
#Question:3
#How to stack two arrays horizontally?
#Desired Output::
#array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
Z_1 = np.hstack((X, Y))
Z_1

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [26]:
#Question:4
#How to convert an array of arrays into a flat 1d array?
#Desired Output::
#array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Y_1 = np.arange(0, 10).reshape(1, 10)
Y_1

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
#Question:5
#How to Convert higher dimension into one dimension?
#Desired Output::
#array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
X_1 = np.arange(0, 15).reshape(1, 5, 3)
Y_1 = X_1.ravel()
Y_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
#Question:6
#Convert one dimension to higher dimension?
#Desired Output::
#array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])
Z_1 = np.reshape(Y_1, (5, 3))
Z_1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [54]:
#Question:7
#Create 5x5 an array and find the square of an array?
Z_01 = np.arange(0, 25).reshape(5, 5)
Z_01

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
np.square(Z_01)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [56]:
#Question:8
#Create 5x6 an array and find the mean?
Z_0 = np.arange(0, 30).reshape(5, 6)
Z_0

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [57]:
np.mean(Z_0)

14.5

In [58]:
#Question:9
#Find the standard deviation of the previous array in Q8?
np.std(Z_0)

8.65544144839919

In [60]:
#Question:10
#Find the median of the previous array in Q8?
np.median(Z_0)

14.5

In [62]:
#Question:11
#Find the transpose of the previous array in Q8?
np.transpose(Z_0)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [63]:
#Question:12
#Create a 4x4 an array and find the sum of diagonal elements?
Y_0 = np.arange(0, 16).reshape(4, 4)
Y_0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.diag(Y_0)

array([ 0,  5, 10, 15])

In [66]:
#Question:13
#Find the determinant of the previous array in Q12?
np.linalg.det(Y_0)

0.0

In [72]:
#Question:14
#Find the 5th and 95th percentile of an array?
np.percentile(Y_0, (5, 95))

array([ 0.75, 14.25])

In [86]:
#Question:15
#How to find if a given array has any null values?
np.where(Y_0 == 0)

(array([0]), array([0]))